### ISSUE TITLE
Strange characters in the listing

### ISSUE THREAD

**Issue by ogamespec** [CodewinBzn/WinASM65#10]
The debug listing contains some strange symbols that look like grave crosses 😱

![image](https://user-images.githubusercontent.com/5828819/164995635-f3f00c80-700b-4897-885d-281dda909e10.png)

Suggestion to replace them with regular spaces, the symbol `|` will still be separated.

**Comment by CodewinBzn** [comment]
@ogamespec bman.lst.tmp is temprary file, it is not the final listing file.
the final listing file is bman.lst ,
you got the bman.lst.tmp because you had an error of assembling that causes a crash.

**Comment by ogamespec** [comment]
Oh, I see.
But in general, with it at least roughly understand how the process of assembling goes, even if there was a crash :)
