### ISSUE TITLE
Combine an assembly script into a single JSON

### ISSUE THREAD

**Issue by ogamespec** [CodewinBzn/WinASM65#11]
The idea of using JSON is very good.

But I see no reason to separate JSON with input rules and JSON with binary layout (results)

**Comment by ogamespec** [comment]
I see no reaction to this Issue.
Feel free to reject the Issue if you don't like it :) That's fine.

**Comment by CodewinBzn** [comment]
Sorry to be late , I'm totally agree with you, there is no need to separate input rules file and binary layout file.
We can have a single JSON file with two sections, one for the inputs the other for the output and both sections will be optional.
I'll fix that in the next commit by the end of the week.
