### ISSUE TITLE
Delete output .nes before build

### ISSUE THREAD

**Issue by ogamespec** [CodewinBzn/WinASM65#12]
The old .nes file is not deleted before building.

**Comment by CodewinBzn** [comment]
Could be deleted in batch script before building.
Is it interesting to modify the assembler in order to delete all future files to generate ?

**Comment by ogamespec** [comment]
Yes, it is better to remove all the files that the assembler produces - by the assembler itself.
This is the usual behavior for this kind of tools, so I didn't even expect that the output files would not be deleted by the assembler itself.
