### ISSUE TITLE
Unable to compile large source code

### ISSUE THREAD

**Issue by ogamespec** [CodewinBzn/WinASM65#6]
I'm trying to build a decompilation of the game Bomberman:

https://github.com/ogamespec/WinASM65/tree/master/bomberman-nes

But WinASM65 crashes with exception:

```
MONSTER_TAB:   --- LABEL

Unhandled exception: System.InvalidOperationException: Stack empty.
   в System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   в System.Collections.Generic.Stack`1.Pop()
   в WinASM65.ExprEvaluator.EvalNode(Stack`1 values, Stack`1 ops)
   в WinASM65.ExprEvaluator.Eval(String expr)
   в WinASM65.Assembler.ResolveExpr(String exprIn, AddrModes addrMode, Boolean isLogical)
   в WinASM65.Assembler.ResolveSymbolDepsAndExprs(UnresolvedSymbol unresSymb)
   в WinASM65.Assembler.ResolveSymbol(String label)
   в WinASM65.Assembler.AddSymbol(String label, Object symb, Boolean replaceIfExist)
   в WinASM65.Assembler.LabelHandler(Match lineReg)
   в WinASM65.Assembler.ProcessLine(Match lineReg, String type)
   в WinASM65.Assembler.ParseLine(String line, String originalLine)
   в WinASM65.Assembler.Process()
   в WinASM65.Assembler.Assemble()
   в WinASM65.MultiSegment.Assemble()
   в WinASM65.Program.Main(String[] args)
```

See make.bat to build the .nes file.

**Comment by CodewinBzn** [comment]
@ogamespec WinAsm65 doesn't work like other assemblers when it comes to .org directive 
You can have only one .org per segment.

**Comment by CodewinBzn** [comment]
@ogamespec do you authorize me to refactor and build  bomberman-nes as an example for WinASM65 ?

**Comment by ogamespec** [comment]
I don't mind 🙂

**Comment by CodewinBzn** [comment]
@ogamespec 
here is the refactored code 
https://github.com/CodewinBzn/WinASM65/tree/master/example_bomberman-nes

I found some syntax errors 

labels are declared in WinASM65 in two ways 
Label: 
  rest of code

label   instruction

**Comment by ogamespec** [comment]
Checked the assembled ROM in Mesen.

Game runs, but then crashes on invalid 6502 opcode.
Looks like 6502 opcode is assembled incorrectly somewhere... I will check it in BinDiff.

![image](https://user-images.githubusercontent.com/5828819/165092614-76b3763c-4f32-49d8-93e9-3cf2dbd2242d.png)

**Comment by CodewinBzn** [comment]
@ogamespec it is assembler error.
The only instructions having zero page,y  are STX and LDX
I'll fix this at late tomorrow

**Comment by CodewinBzn** [comment]
@ogamespec the fix is now available in the last commit

**Comment by ogamespec** [comment]
I am not able to pull the master because it contains build/WinASM65.exe and this causes a conflict.

**Comment by ogamespec** [comment]
But after building with parts from Assembler.cs / CPUDefs.cs - nothing has changed. Still the same garbled screen, after the splash screen.

**Comment by CodewinBzn** [comment]
I build it serveral times and the game works fine.
I think you need to resolve the conflicts or download the WinASM65 project zip and build it.

**Comment by CodewinBzn** [comment]
@ogamespec I can't reproduce the bug with the last commit

**Comment by ogamespec** [comment]
Well I resolved the conflicts, but in the list of changes there is no code to fix STX and LDX.

![image](https://user-images.githubusercontent.com/5828819/165168944-f14750dc-2ff7-47a8-a266-2e3da3baa3e5.png)

![image](https://user-images.githubusercontent.com/5828819/165168995-9fd3e91a-b903-4529-8e6a-234d9444ebfe.png)

**Comment by CodewinBzn** [comment]
Yes it is done by the following line

 if (CPUDef.IsAbsoluteAddr(addrMode) && exprRes.Result <= 255 **&& addrModesValues[(int)addrMode+3] != 0xff**)

**Comment by ogamespec** [comment]
hmmm....
Maybe the old .nes file is not deleted before building.

**Comment by ogamespec** [comment]
Yes, I confirm, everything works fine now 😄 

![image](https://user-images.githubusercontent.com/5828819/165170234-33eedcdf-9434-4f39-b335-04e88196dad6.png)

**Comment by CodewinBzn** [comment]
Glad to see that :smiley:
